on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest
        uses: WPO-Foundation/webpagetest-github-action@v.1.0.0
        with:
          apiKey: ${{ secrets.WPT_API_KEY_TAPESTRY }}
          urls: |
            https://google.com/
            https://google.com/about
          label: 'GitHub Action Test'
          wptOptions: '.github/tests/wpt-options.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}